// See LICENSE for full copyright and licensing information.

#pragma once

#define PACKER_VERSION_STRING MAKE_STRING(PACKER_VERSION_MAJOR) "." MAKE_STRING(PACKER_VERSION_MINOR) "." MAKE_STRING(PACKER_VERSION_PATCH)
