name: Build workflow

on:
  push:
    branches:
      - main  # Change this to the branch you want to trigger the workflow on

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Install dependencies
        run: npm install

      - name: Build and deploy
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}  # Access the secret here
        run: |
          # Use the GH_TOKEN environment variable in your build and deployment steps
          # For example, you can use it to authenticate with GitHub API or access private repositories.
          echo "Using GitHub Token: $GH_TOKEN"
          # Your build and deployment commands here
