name: CI

on:
  push:
    branches:
      - main

jobs:
  setup-python:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8  # Adjust the version as needed

  install-dependencies:
    needs: setup-python
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          # Additional setup steps if needed

  run-tests:
    needs: install-dependencies
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run tests
        run: |
          python RunTests.py

  cmake-build-and-test:
    needs: install-dependencies
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build and test with CMake
        run: |
          mkdir build
          cd build
          cmake ..
          cmake --build .
          ctest --output-on-failure  # Run tests and display output on failure
