name: Generate Documentation

on:
  push:
    paths:
      - 'GenerateDocs.py'
      - 'Source/Packer/**'
      - 'Source/Console/**'

jobs:
  generate-docs:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        # Add any other dependencies here

    - name: Install Doxygen
      run: sudo apt-get install doxygen

    - name: Generate Documentation
      run: python GenerateDocs.py

    - name: Commit Documentation to New Branch
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git pull origin master  # Ensure we are up-to-date with master
        git checkout -b docs-update-${{ github.run_id }}  # Create a new branch with a
